# Generated by Django 3.2.14 on 2024-01-19 13:07

import django.core.files.storage
from django.db import migrations, models
import onlineforms.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforms', '0006_fill_file_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmissionfile',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=onlineforms.models.attachment_upload_to),
        ),
    ]
