# Generated by Django 3.2.14 on 2025-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforms', '0007_trivial_migration_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='progress_bar',
            field=models.BooleanField(default=False, help_text='Should submissions display a progress bar?'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='progress_bar',
            field=models.BooleanField(default=False, help_text='Should this sheet display to form fillers in a progress bar, if enabled?'),
        ),
    ]
