# Generated by Django 3.2.14 on 2025-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforms', '0007_trivial_migration_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='progress_bar',
            field=models.BooleanField(default=False, help_text='Should submissions display a progress bar? Select sheets and their order on the following page.'),
        ),
    ]
