import random
from datetime import timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from coredata.models import Person, Unit
from postdoc.models import PostDoc, PostDocFundingSource, PostDocSupervisor


TYPE_CHOICES = ['INTERNAL', 'EXTERNAL_SFU', 'EXTERNAL_NON_SFU', 'BOTH']
WORK_ELIGIBILITY_CHOICES = ['CANADIAN_CITIZEN', 'PERMANENT_RESIDENT', 'INTERNATIONAL']
WORK_HOURS_CHOICES = ['FULL_TIME', 'PART_TIME']
DEPT_CHOICES = [2110, 2130, 2140, 2150, 2020, 2030]
FUND_CHOICES = [11, 13, 21, 23, 25, 29, 31, 32, 35, 36, 37, 38, 40]


class Command(BaseCommand):
    help = 'Seed random PostDoc records for development/testing.'

    def add_arguments(self, parser):
        parser.add_argument('--count', type=int, default=100, help='Number of PostDoc records to create (default: 100).')

    def handle(self, *args, **options):
        count = options['count']
        if count <= 0:
            raise CommandError('--count must be greater than 0.')

        people = list(Person.objects.filter(emplid__isnull=False))
        units = list(Unit.objects.all())

        if len(people) < 2:
            raise CommandError('Need at least two Person records with emplid to seed PostDocs.')
        if not units:
            raise CommandError('Need at least one Unit record to seed PostDocs.')

        created = 0
        today = timezone.now().date()

        while created < count:
            person = random.choice(people)
            unit = random.choice(units)

            supervisor_pool = [p for p in people if p.id != person.id]
            if not supervisor_pool:
                continue

            start_date = today + timedelta(days=random.randint(-365, 365))
            end_date = start_date + timedelta(days=random.randint(120, 730))

            is_lump_sum = random.random() < 0.25
            work_hours = random.choice(WORK_HOURS_CHOICES)
            is_relocation = random.random() < 0.2

            # use one selected supervisor as last_updater so this is always valid
            updater = random.choice(supervisor_pool)

            appt = PostDoc(
                person=person,
                unit=unit,
                type=random.choice(TYPE_CHOICES),
                doctorate_completed_date=start_date - timedelta(days=random.randint(365, 3650)),
                work_eligibility_status=random.choice(WORK_ELIGIBILITY_CHOICES),
                relocation_reimbursement=is_relocation,
                relocation_reimbursement_amount=Decimal(str(round(random.uniform(500, 6000), 2))) if is_relocation else Decimal('0.00'),
                involved_teaching=(random.random() < 0.3),
                other_info='Auto-generated sample record',
                start_date=start_date,
                end_date=end_date,
                benefits_estimation=Decimal(str(round(random.uniform(10, 25), 2))),
                work_hours=work_hours,
                hours_of_work=Decimal(str(round(random.uniform(10, 34), 2))) if work_hours == 'PART_TIME' else Decimal('35.00'),
                vacation_entitlement_weeks=Decimal(str(round(random.choice([2.0, 3.0, 4.0]), 2))),
                annual_salary_amount=None if is_lump_sum else Decimal(str(round(random.uniform(45000, 95000), 2))),
                lump_sum_payment=Decimal(str(round(random.uniform(5000, 50000), 2))) if is_lump_sum else None,
                deleted=False,
                last_updater=updater,
            )
            appt.admin_notes = 'Generated by seed_postdocs command.'
            appt.save()

            # supervisors: at least 1, up to 5 (or pool size)
            sup_count = random.randint(1, min(5, len(supervisor_pool)))
            chosen_supervisors = random.sample(supervisor_pool, sup_count)
            for sup in chosen_supervisors:
                PostDocSupervisor.objects.create(
                    postdoc=appt,
                    supervisor=sup,
                )

            # funding sources: min 1, max 3
            num_sources = random.randint(1, 3)
            for i in range(num_sources):
                fund = random.choice(FUND_CHOICES)
                PostDocFundingSource.objects.create(
                    postdoc=appt,
                    unit=random.choice(DEPT_CHOICES),
                    fund=fund,
                    project='' if (fund == 11 or random.random() < 0.2)
                    else random.choice(['R', 'X', 'S', 'N']) + str(random.randint(100000, 999999)),
                    amount=Decimal(str(round(random.uniform(1000, 50000), 2))),
                    start_date=start_date + timedelta(days=30 * i),
                    end_date=end_date,
                )

            created += 1

        self.stdout.write(self.style.SUCCESS(f'Created {created} PostDoc records.'))