import random
from datetime import timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from coredata.models import Person, Unit
from postdoc.models import PostDoc


TYPE_CHOICES = ['INTERNAL', 'EXTERNAL_SFU', 'EXTERNAL_NON_SFU', 'BOTH']
WORK_ELIGIBILITY_CHOICES = ['CANADIAN_CITIZEN', 'PERMANENT_RESIDENT', 'INTERNATIONAL']
WORK_HOURS_CHOICES = ['FULL_TIME', 'PART_TIME']
DEPT_CHOICES = [2110, 2130, 2140, 2150, 2020, 2030]
FUND_CHOICES = [11, 13, 21, 23, 25, 29, 31, 32, 35, 36, 37, 38, 40]


class Command(BaseCommand):
    help = 'Seed random PostDoc records for development/testing.'

    def add_arguments(self, parser):
        parser.add_argument('--count', type=int, default=100, help='Number of PostDoc records to create (default: 100).')

    def handle(self, *args, **options):
        count = options['count']
        if count <= 0:
            raise CommandError('--count must be greater than 0.')

        people = list(Person.objects.filter(emplid__isnull=False))
        units = list(Unit.objects.all())

        if len(people) < 2:
            raise CommandError('Need at least two Person records with emplid to seed PostDocs.')
        if not units:
            raise CommandError('Need at least one Unit record to seed PostDocs.')

        created = 0
        today = timezone.now().date()

        while created < count:
            person = random.choice(people)
            supervisors = [p for p in people if p.id != person.id]
            supervisor = random.choice(supervisors)
            secondary_supervisor = random.choice(supervisors) if random.random() < 0.35 else None
            unit = random.choice(units)

            start_date = today + timedelta(days=random.randint(-365, 365))
            end_date = start_date + timedelta(days=random.randint(120, 730))

            is_lump_sum = random.random() < 0.25
            work_hours = random.choice(WORK_HOURS_CHOICES)
            is_relocation = random.random() < 0.2

            fs2_option = random.random() < 0.4
            fs3_option = fs2_option and random.random() < 0.35

            appt = PostDoc(
                person=person,
                unit=unit,
                supervisor=supervisor,
                secondary_supervisor=secondary_supervisor,
                type=random.choice(TYPE_CHOICES),
                doctorate_completed_date=start_date - timedelta(days=random.randint(365, 3650)),
                work_eligibility_status=random.choice(WORK_ELIGIBILITY_CHOICES),
                relocation_reimbursement=is_relocation,
                relocation_reimbursement_amount=Decimal(str(round(random.uniform(500, 6000), 2))) if is_relocation else Decimal('0.00'),
                involved_teaching=(random.random() < 0.3),
                other_info='Auto-generated sample record',
                start_date=start_date,
                end_date=end_date,
                benefits_estimation=Decimal(str(round(random.uniform(10, 25), 2))),
                work_hours=work_hours,
                hours_of_work=Decimal(str(round(random.uniform(10, 34), 2))) if work_hours == 'PART_TIME' else Decimal('35.00'),
                vacation_entitlement_weeks=Decimal(str(round(random.choice([2.0, 3.0, 4.0]), 2))),
                annual_salary_amount=None if is_lump_sum else Decimal(str(round(random.uniform(45000, 95000), 2))),
                lump_sum_payment=Decimal(str(round(random.uniform(5000, 50000), 2))) if is_lump_sum else None,
                fs1_unit=random.choice(DEPT_CHOICES),
                fs1_fund=random.choice(FUND_CHOICES),
                fs1_project='' if random.random() < 0.2 else random.choice(['R', 'X', 'S', 'N']) + str(random.randint(100000, 999999)),
                fs2_unit=random.choice(DEPT_CHOICES) if fs2_option else 0,
                fs2_fund=random.choice(FUND_CHOICES) if fs2_option else 0,
                fs2_project=('' if random.random() < 0.2 else random.choice(['R', 'X', 'S', 'N']) + str(random.randint(100000, 999999))) if fs2_option else '',
                fs3_unit=random.choice(DEPT_CHOICES) if fs3_option else 0,
                fs3_fund=random.choice(FUND_CHOICES) if fs3_option else 0,
                fs3_project=('' if random.random() < 0.2 else random.choice(['R', 'X', 'S', 'N']) + str(random.randint(100000, 999999))) if fs3_option else '',
                deleted=False,
                last_updater=supervisor,
            )
            appt.fs2_option = fs2_option
            appt.fs3_option = fs3_option
            appt.admin_notes = 'Generated by seed_postdocs command.'
            appt.save()
            created += 1

        self.stdout.write(self.style.SUCCESS(f'Created {created} PostDoc records.'))
